export enum TemplateName {
  AccountFundingSuccessful = "AccountFundingSuccessful",
  AdminAccountCreated = "AdminAccountCreated",
  EmailVerification = "EmailVerification",
  EmployeeInvitation = "EmployeeInvitation",
  KYCApproved = "KYCApproved",
  UserLogin = "UserLogin",
  PayrollSuccessfulBusiness = "PayrollSuccessfulBusiness",
  PayrollSuccessfulEmployee = "PayrollSuccessfulEmployee",
  PasswordReset = "PasswordReset",
  UnresolvedAccountsImport = "UnresolvedAccountsImport",
  Welcome = "Welcome",
  PayrollReminder = "PayrollReminder",
  PayrollAutoApprovalSuccessful = "PayrollAutoApprovalSuccessful",
  PayrollAutoPilotDisable = "PayrollAutoPilotDisable",
  PayrollAutoApprovalFailed = "PayrollAutoApprovalFailed",
  PayrollAutoPilotEnabled = "PayrollAutoPilotEnabled",
  PayrollAutoPilotDisabled = "PayrollAutoPilotDisabled",
  PayrollProcessing = "PayrollProcessing",
}
